mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('pokemon.urls'))
]

pokemon/urls.py
from django.contrib import admin
from django.urls import path
from pokemon import views
from django.conf.urls.static import static
from django.conf import settings

app_name="pokemon"

urlpatterns = [
    path("",views.home,name="pokemon"),
    path("pokefeaname",views.pokefeaname,name="pokefeaname"),
    path("pokefea",views.pokefea,name="pokefea"),
    path("upload",views.upload,name="upload")
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pokemon/models.py
from django.db import models

# Create your models here.

pokemon/views.py
from django.shortcuts import render, redirect
import pandas as pd
import sqlite3

# Create your views here.
def home(request):
    return render(request, 'home.html')


def pokefeaname(request):
    if request.method == "POST":
        pokemon_name = request.POST.get('pokemon-name')
        pokemon_name = pokemon_name.title()
        # sqlite3 query
        conn = sqlite3.connect('db.sqlite3')
        c = conn.cursor()
        c.execute("SELECT * FROM pokemon WHERE Name=?", (pokemon_name,))
        names = c.fetchall()
        conn.commit()
        conn.close()
        
        if len(names) == 0:
            return render(request, "pokemon.html", {"value":0})
        else:
            for name in names:
                dict = {"Name": name[2], "Type1": name[3], "Type2": name[4], "Total": name[5], "HP": name[6], "attack": name[7],
                        "defence": name[8], "S_A": name[9], "S_D": name[10], "speed": name[11], "generation": name[12], "legendary": name[13]}
            return render(request, "pokemon.html", dict)
    return redirect("/")

def pokefea(request):
    if request.method=="POST":
        type=request.POST.get('pokfea')
        type=type.title()
        list=[]
        conn=sqlite3.connect('db.sqlite3')
        c=conn.cursor()
        c.execute("SELECT * FROM pokemon WHERE Type1=?",(type,))
        poke=c.fetchall()
        for i in poke:
            list.append(i[2])
        conn.commit()
        conn.close()
        type=type.upper()
    return render(request,'pokesearch.html',{"type": type,"list":list})



def upload(request):
    conn = sqlite3.connect('db.sqlite3')
    df = pd.read_excel(r"pokemon.csv")
    df.to_sql(con=conn, name='pokemon', if_exists='append')
    conn.commit()
    conn.close()
    return render(request, 'home.html')

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href={% static 'css/home.css' %}>
    <link rel="shortcut icon" type="image/png" href="{%static 'img\logo.png'%}"/>

</head>


<body>

    <div id="outer">
        <div id="image">
        </div>
        <div id="inner">
            <form action="{% url 'pokemon:pokefeaname' %}" method="post">
                {% csrf_token %}
                <p><b>SEARCH BY POKEMON NAME</b></p>
                <input type="text" name="pokemon-name" id="pname" required placeholder="Pokemon">
                <div id="button">
                    <input type="submit"></input>
                </div>
            </form>
            <form action="{% url 'pokemon:pokefea' %}" method="post">
                {% csrf_token %}
                <p><b>SEARCH BY POKEMON TYPE</b></p>
                <select name="pokfea">
                    <option value="bug">BUG</option>
                    <option value="dark">DARK</option>
                    <option value="dragon">DRAGON</option>
                    <option value="electric">ELECTRIC</option>
                    <option value="fairy">FAIRY</option>
                    <option value="fighting">FIGHTING</option>
                    <option value="flying">FLYING</option>
                    <option value="fire">FIRE</option>
                    <option value="grass">GRASS</option>
                    <option value="ghost">GHOST</option>
                    <option value="ground">GROUND</option>
                    <option value="ice">ICE</option>
                    <option value="normal">NORMAL</option>
                    <option value="posion">POSION</option>
                    <option value="psychic">PSYCHIC</option>
                    <option value="rock">ROCK</option>
                    <option value="steel">STEEL</option>
                    <option value="water">WATER</option>
                </select><br>
                <div id="button">
                    <input type="submit"></input>
                </div>
            </form>
            {% comment %} <form action="{% url 'pokemon:upload' %}" method="post">
                {% csrf_token %}
                <input type="submit"></input>
            </form> {% endcomment %}
        </div>
    </div>
    <audio loop="true" autoplay="true" id="auto">
        <source src="/static/music/Pokemon_Theme_Song.mp3" type="audio/mp3">
    </audio>
</body>

<script>
    window.onload = function () {
        docuement.getElementById("auto").play();
    }
</script>

</html>

templates/pokesearch.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pokemon search</title>
    <link rel="stylesheet" href={% static 'css/page2.css' %}>
    <link rel="shortcut icon" type="image/png" href="{%static 'img\logo.png'%}"/>

</head>


<body>
    <div id="image">
        
    </div>
    <div id="image1">
 
    <div id="form">

        <p><b>Type : {{type}}</b></p>
        <form action="{% url 'pokemon:pokefeaname' %}" method="post">
            {% csrf_token %}
            <select name="pokemon-name" id="pokefea">
                {% for x in list %}
                {% comment %} <button type="submit" value="choice{{ x }}">{{x}}</button> {% endcomment %}
                <option value="{{x}}">{{x}}</option>
                {% endfor %}
                <br>
            </select>
            <input type="submit" onclick="playAudio"></input>
        </form>
    <audio loop="true" autoplay="true" id="audio">
        <source src="/static/music/Pokemon_Theme_Song.mp3" type="audio/mp3">
    </audio>
  <input type="image" name="submit" onclick="volume()" src="/static/img/unmute.png" border="0" alt="Submit" id="volimg" style="width: 50px;height: 50px" /> 
    </div>
</div>

<script>
    let aud = document.getElementById("audio");

    var count = 0;

    var x = document.getElementById("audio");

    function playAudio() {
        x.play();
    }


    function volume() {
        if (count % 2 == 0) {
            Mute();
            count = count + 1;
        }
        else {
            Unmute();
            count = count + 1;
        }
    }
    function Mute() {
        aud.volume = 0;
        document.getElementById("volimg").src = "/static/img/mute.png"
    }

    function Unmute() {
        aud.volume = 1.0;
        document.getElementById("volimg").src = "/static/img/unmute.png"

    } 
</script>

</body>

</html>